env:
  env-name: CartPole-v1

socket:
  ip: 127.0.0.1
  port: 23333

learner:
  seed: 2021
  learning_steps: 1
  max_grad_norm: 1.0
  clip: 0.2
  lr: 0.0002
  lr_decay: 1.0  
  lr_decay_every: 1
  entropy_regularization: 0.01
  entropy_regularization_decay: 0.99
  lambda: 1.0
  gamma: 0.99
  loss_target: ppo_loss  
  eval_every: 3
  solve_score: 200
  result_dir: /home/kvu/ddrl/benchmarks/openai-gyms/CartPole-v1/

batcher:
  batch_size: 512
  buffer_size: 10

worker:
  max_t: 1000
  buffer_size: 1024
  sync_every: 3