env:
  env-name: LunarLanderContinuous-v2

learner:
  socket:
    ip: 127.0.0.1
    port: 23333

  network:
    gru_seq_len: 4
    batch_size: 1024
    learning_steps: 3
    clip: 0.15
    lr: 0.0003

  batcher:
    buffer_size: 10000
    gamma: 0.95

  utils:
    seed: 2021

worker:
  max_t: 500
  batch_size: 2048
  save_every: 200
  sync_every: 3
  