env:
  env-name: LunarLanderContinuous-v2

learner:
  socket:
    ip: 127.0.0.1
    port: 23333

  network:
    batch_size: 128
    learning_steps: 5
    clip: 0.2
    lr: 0.0003

  batcher:
    buffer_size: 20000
    gamma: 0.95

  utils:
    seed: 2021

worker:
  max_t: 200
  batch_size: 1024
  save_every: 25
  sync_every: 10
  