env:
  env-name: LunarLanderContinuous-v2

learner:
  socket:
    ip: 127.0.0.1
    port: 23333

  network:
    rnn_seq_len: 10
    batch_size: 1024
    learning_steps: 3
    max_grad_norm: 1.0
    clip: 0.1
    lr: 0.0005
    lambda: 0.9
    loss_target: vtrace

  batcher:
    buffer_size: 1000
    gamma: 0.99

  utils:
    seed: 2021
  
  eval_every: 100

worker:
  max_t: 512
  batch_size: 4096
  save_every: 200
  sync_every: 3

debug: False

neptune:
  project: khanhvu207/ddrl
  api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI3MzYwMjRlNy1mOGZiLTQ1YjYtOWU4OS1mY2E4Y2EwZmRlY2EifQ==