env:
  env-name: LunarLander-v2

socket:
  ip: 127.0.0.1
  port: 23333

learner:
  seed: 2021
  learning_steps: 1
  max_grad_norm: 1.0
  clip: 0.1
  lr: 0.0002
  lr_decay: 0.0
  lr_decay_every: 1
  entropy_regularization: 0.1
  entropy_regularization_decay: 0.99
  lambda: 0.95
  gamma: 0.99
  loss_target: ppo_loss
  eval_every: 3
  solve_score: 200
  result_dir: /home/kvu/ddrl/benchmarks/openai-gyms/LunarLander-v2/

batcher:
  batch_size: 1024
  buffer_size: 10

worker:
  max_t: 1000
  buffer_size: 1024
  sync_every: 1