env:
  env-name: MountainCar-v0

socket:
  ip: 127.0.0.1
  port: 23333

learner:
  seed: 2021
  learning_steps: 3
  max_grad_norm: 1.0
  clip: 0.2
  lr: 0.0002
  lr_decay: 1.0 
  lr_decay_every: 1
  entropy_regularization: 0.01
  entropy_regularization_decay: 0.99
  lambda: 0.95
  gamma: 0.99
  loss_target: td_lambda
  eval_every: 3
  solve_score: -125
  result_dir: /home/kvu/ddrl/benchmarks/openai-gyms/MountainCar-v0/

batcher:
  batch_size: 512
  buffer_size: 20

worker:
  max_t: 1024
  buffer_size: 1024
  sync_every: 3